usr/lib/libfeelpp.so
#usr/lib/libfeelpp_metis.so
usr/lib/libfeelpp_gflags.so
usr/lib/libfeelpp_gflags_nothreads.so
usr/lib/libfeelpp_ginac.so
usr/lib/libfeelpp_glog.so
usr/lib/*/libfeelpp_nlopt.so
#usr/lib/libfeelpp_nlopt.so

# usr/lib/libfeelpp_modelalg.so
# usr/lib/libfeelpp_modelmesh.so
# usr/lib/libfeelpp_modelcore.so
# usr/lib/libfeelpp_modelmeshale.so

#usr/include/feel
usr/include/feelpp

usr/share/feelpp
